server:
  port: 9001

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000 # // try to replace it with eureka discovery alternative : "http://STS-SPRING-BOOT-AUTHORIZATION-SERVER"