spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

# Configuration pour les appels à l'Authorization Server
authorization:
  server:
    url: http://localhost:8764/oauth2/token
    ms1:
      client-id: client1
      client-secret: secret1
    ms2:
      client-id: client2
      client-secret: secret2

# URLs de l'API Gateway pour les appels aux microservices
api:
  gateway:
    url: http://localhost:7766